# design.py - The 1444 New World realm table for "States of the New World" mod.
# Field meaning:
#   tag, name, adj          - country tag, display name (loc), adjective (loc)
#   reuse                   - True: vanilla country def + (mostly) vanilla loc kept.
#                             False: generate common/countries/<Name>.txt + loc.
#   filenote                - "vanilla" for reused tags: history filename = vanilla
#                             file name (auto-detected), so the vanilla file is overridden.
#   color                   - [r,g,b] used only for new tags.
#   (gov/reform/rank fields were removed: every realm is a feudal monarchy in gen_mod; the
#   government_rank comes from total development there: 1 < 20, 2 >= 20, 3 only Aztec)
#   dev                     - [base_tax, base_production, base_manpower] per province (capital +1 each)
#   capital                 - province id (or None -> smallest id of first area)
#   areas                   - area names to take ALL provinces from
#   extra                   - extra province ids (strays like Bermuda, Galapagos, 1802/1803)
#   trade_good              - trade_goods line for every province of the realm
#   culture                 - None -> mode of assigned provinces' vanilla culture
#   religion                - None -> mode of assigned provinces' vanilla religion
#   tech, unit              - technology_group / unit_type
#   graphical_culture       - for new tags only
#   monarchs                - [{name, dynasty, adm, dip, mil, birth}, ...] first = current ruler
#   heir                    - optional {name, dynasty, claim, adm, dip, mil, birth, death}
#   names                   - monarch_names pool for new tags
#   ideas                   - historical_idea_groups for new tags

REALMS = [
# ---------------------------------------------------------------- ALASKA / PACIFIC NW
dict(tag="ALA", name="Alaska", adj="Alaskan", reuse=True, areas=["alaska_area","east_alaska_area"], capital=978,
        dev=[3,3,3], trade_good="fur",
     monarchs=[dict(name="Tlingit", dynasty="Kwaan", adm=1, dip=3, mil=2, birth=1408)],
     heir=dict(name="Kichxáan", dynasty="Kwaan", claim=80, adm=2, dip=2, mil=2, birth=1428, death=1490)),
dict(tag="CSC", name="Cascadia", adj="Cascadian", reuse=True,
     areas=["salish_sea_area","columbia_river_area","oregon_area","straits_of_georgia_area","hecate_strait_area","interior_plateau_area"],
     capital=2484,    dev=[3,3,4], trade_good="fur",
     monarchs=[dict(name="Stephen", dynasty="Fraser", adm=3, dip=3, mil=3, birth=1399)],
     heir=dict(name="Thomas", dynasty="Fraser", claim=88, adm=3, dip=3, mil=3, birth=1424, death=1486)),
# ---------------------------------------------------------------- CALIFORNIA / DESERT SW
dict(tag="CAL", name="California", adj="Californian", reuse=True,
     areas=["california_area","central_valley_area","northern_california_area","baja_california_area"],
     capital=868,    dev=[4,4,4], trade_good="grain",
     monarchs=[dict(name="Ramiro", dynasty="de Baja", adm=3, dip=4, mil=4, birth=1396)],
     heir=dict(name="Violante", dynasty="de Baja", claim=90, adm=3, dip=4, mil=3, birth=1425, death=1492)),
dict(tag="ARZ", name="Arizona", adj="Arizonan", reuse=False, color=[216,197,150],
     areas=["arizona_area"], capital=867,    dev=[3,3,3],
     trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="James", dynasty="Saddleback", adm=2, dip=2, mil=3, birth=1405)],
     names=["James","Noel","Marcus","Peter","Hugh","Simon","Walt","Owen"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="CIB", name="Cibola", adj="Cibolan", reuse=False, color=[181,94,58],
     areas=["new_mexico_area","apacheria_area"], capital=881,  
      dev=[3,3,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Edward", dynasty="of the Seven Cities", adm=3, dip=2, mil=3, birth=1402)],
     heir=dict(name="Peter", dynasty="of the Seven Cities", claim=85, adm=2, dip=2, mil=3, birth=1426, death=1488),
     names=["Edward","Peter","Lucas","Martin","Wesley","Corbin","Allen","Grant"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="DSR", name="Deseret", adj="Deseretan", reuse=False, color=[212,164,40],
     areas=["snake_river_area","badlands_area"], capital=2490,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Brigham", dynasty="of the Beehive", adm=3, dip=2, mil=2, birth=1400)],
     names=["Brigham","Hyrum","Ephraim","Lehi","Moses","Aaron","Nehemiah","Josiah"],
     ideas=["defensive_ideas","economic_ideas","trade_ideas"]),
dict(tag="CLD", name="Colorado", adj="Coloradan", reuse=False, color=[91,139,190],
     areas=["high_plains_area","colorado_plateau_area"], capital=889,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Sterling", dynasty="of the Front Range", adm=2, dip=2, mil=3, birth=1404)],
     names=["Sterling","Canon","Pueblo","Durango","Aspen","Gunnison","Rifle","Salida"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="BTR", name="Bitterroot", adj="Bitterroot", reuse=False, color=[120,156,110],
     areas=["upper_missouri_area"], capital=2006,  
      dev=[3,3,3], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Kolby", dynasty="of the Divide", adm=2, dip=2, mil=3, birth=1407)],
     names=["Kolby","Ronan","Dillon","Havre","Eureka","Bozeman","Kalispell","Anaconda"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
# ---------------------------------------------------------------- PLAINS / MIDWEST
dict(tag="DKT", name="Dakota", adj="Dakotan", reuse=False, color=[155,177,200],
     areas=["dakota_area","south_dakota_area"], capital=906,  
      dev=[3,3,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Everett", dynasty="of the Badlands", adm=2, dip=3, mil=3, birth=1403)],
     heir=dict(name="Selby", dynasty="of the Badlands", claim=82, adm=2, dip=2, mil=3, birth=1427, death=1489),
     names=["Everett","Selby","Edmund","Bismarck","Huron","Faulk","Potter","Cavalier"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="NST", name="North Star", adj="Northstar", reuse=False, color=[138,166,196],
     areas=["minnessota_area","lake_superior_area","red_river_area"], capital=904, 
       dev=[3,3,4], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Vaughan", dynasty="of the Lakes", adm=3, dip=3, mil=3, birth=1401)],
     heir=dict(name="Loran", dynasty="of the Lakes", claim=85, adm=2, dip=3, mil=2, birth=1428, death=1491),
     names=["Vaughan","Loran","Anoka","Cass","Itasca","Mille","Otter","Pipestone"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="WIS", name="Wisconsin", adj="Wisconsinite", reuse=False, color=[124,143,168],
     areas=["wisconsin_area"], capital=912,   
     dev=[3,3,3], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Gordon", dynasty="of the Door", adm=2, dip=2, mil=3, birth=1406)],
     names=["Gordon","Menominee","Oconto","Racine","Sauk","Waukesha","Winnebago","Sheboygan"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="IOW", name="Iowa", adj="Iowan", reuse=False, color=[185,194,104],
     areas=["iowa_area"], capital=905,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Cyrus", dynasty="of the Loess", adm=2, dip=2, mil=3, birth=1405)],
     names=["Cyrus","Dubuque","Davenport","Keokuk","Osceola","Plymouth","Sioux","Tama"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="KNS", name="Kansas", adj="Kansan", reuse=False, color=[214,197,138],
     areas=["kansas_area","central_plains_area"], capital=890,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Abilene", dynasty="of the Flint Hills", adm=2, dip=2, mil=3, birth=1404)],
     names=["Abilene","Osage","Sedgwick","Wichita","Salina","Cottonwood","Neosho","Solomon"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="OKH", name="Oklahoma", adj="Oklahoman", reuse=False, color=[201,142,90],
     areas=["lower_plains_area"], capital=891,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Cherokee", dynasty="of the Red Earth", adm=2, dip=3, mil=2, birth=1408)],
     names=["Cherokee","Choctaw","Comanche","Kiowa","Osage","Seminole","Caddo","Tonkawa"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="TEX", name="Texas", adj="Texan", reuse=True,
areas=["texas_area","texas_plains_area","coastal_prarie_area","pecos_area","llano_estacado_area"],
      capital=885,    dev=[4,4,4], trade_good="grain",
     monarchs=[dict(name="Moses", dynasty="of the Brazos", adm=3, dip=4, mil=4, birth=1395)],
     heir=dict(name="Houston", dynasty="of the Brazos", claim=90, adm=4, dip=3, mil=4, birth=1420, death=1493)),
dict(tag="LOU", name="Louisiana", adj="Louisianan", reuse=True,
     areas=["mississippi_plain_area","lower_louisiana_area"], capital=893, 
       dev=[3,3,4], trade_good="sugar",
     monarchs=[dict(name="Jean-Baptiste", dynasty="de Bienville", adm=2, dip=4, mil=3, birth=1399)],
     heir=dict(name="Marie-Josephe", dynasty="de Bienville", claim=85, adm=3, dip=3, mil=2, birth=1424, death=1488)),
dict(tag="OZK", name="Ozarkia", adj="Ozarkan", reuse=False, color=[122,150,96],
     areas=["ozarks_area","upper_louisiana_area"], capital=899,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Osage", dynasty="of the White River", adm=2, dip=3, mil=3, birth=1404)],
     names=["Osage","White River","Springfield","Joplin","Eureka","Buffalo","Taney","Table Rock"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="MGA", name="Michigania", adj="Michiganian", reuse=False, color=[90,138,160],
     areas=["michigan_area"], capital=2521,   
     dev=[3,3,3], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Mackinac", dynasty="of the Straits", adm=2, dip=3, mil=2, birth=1407)],
     names=["Mackinac","Huron","Saginaw","Ottawa","Leelanau","Charlevoix","Emmet","Alpena"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="OHI", name="Ohio", adj="Ohioan", reuse=False, color=[176,72,112],
     areas=["ohio_country_area"], capital=946,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Tecumseh", dynasty="of the Mounds", adm=2, dip=2, mil=4, birth=1400)],
     names=["Tecumseh","Wyandot","Shawnee","Miami","Scioto","Cuyahoga","Muskingum","Hocking"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="WAB", name="Wabash", adj="Wabashan", reuse=False, color=[107,155,212],
     areas=["miami_river_area"], capital=942,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Kekionga", dynasty="of the Portage", adm=2, dip=2, mil=3, birth=1406)],
     names=["Kekionga","Wabash","Tippecanoe","Vermillion","Piankeshaw","Wea","Ouiatenon","Potawatomi"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="ILI", name="Illinois", adj="Illinoisan", reuse=True,
     areas=["illinois_country_area","southern_illinois_area"], capital=4903, 
       dev=[3,3,4], trade_good="grain",
     monarchs=[dict(name="Cahokia", dynasty="of the Mississippians", adm=2, dip=3, mil=3, birth=1399)],
     heir=dict(name="Kaskaskia", dynasty="of the Mississippians", claim=84, adm=2, dip=3, mil=2, birth=1425, death=1487)),
# ---------------------------------------------------------------- SOUTH EAST USA
dict(tag="CMB", name="Cumberland", adj="Cumberland", reuse=False, color=[139,102,94],
     areas=["kentucky_area","western_kentucky_area"], capital=940, 
       dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Harrods", dynasty="of the Caves", adm=2, dip=2, mil=3, birth=1405)],
     names=["Harrods","Boone","Logan","Maysville","Owensboro","Paducah","Richmond","Somerset"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="TNS", name="Tanasi", adj="Tanasian", reuse=False, color=[176,117,85],
     areas=["choctaw_area","south_appalachia_area"], capital=918, 
       dev=[3,3,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Tsali", dynasty="of the Smoky Range", adm=2, dip=3, mil=3, birth=1401)],
     heir=dict(name="Dragging Canoe", dynasty="of the Smoky Range", claim=86, adm=3, dip=2, mil=3, birth=1426, death=1493),
     names=["Tsali","Junaluska","Sequoyah","Oconostota","Attakullakulla","Nicot","Yonaguska","Standing Deer"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="MSP", name="Mississippi", adj="Mississippian", reuse=False, color=[104,140,140],
     areas=["mississippi_area"], capital=4884,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Natchez", dynasty="of the Great Sun", adm=3, dip=2, mil=2, birth=1403)],
     names=["Natchez","Yazoo","Chickasaw","Choctaw","Biloxi","Tunica","Houma","Chakchiuma"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="ALM", name="Alabama", adj="Alabaman", reuse=False, color=[110,155,196],
     areas=["alabama_area"], capital=924,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Tuskaloosa", dynasty="of the Black Warrior", adm=2, dip=2, mil=3, birth=1404)],
     names=["Tuskaloosa","Coosa","Tallapoosa","Autauga","Escambia","Muskogee","Tensaw","Ocmulgee"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="GEA", name="Georgia", adj="Georgian", reuse=False, color=[185,107,46],
     areas=["american_georgia_area","upper_american_georgia_area"], capital=929, 
       dev=[3,3,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Okefenokee", dynasty="of the Marshes", adm=2, dip=3, mil=3, birth=1402)],
     heir=dict(name="Mocama", dynasty="of the Marshes", claim=83, adm=2, dip=2, mil=3, birth=1427, death=1488),
     names=["Okefenokee","Mocama","Yamasee","Hitchiti","Muskogee","Seminola","Apalachee","Ogeechee"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="FLO", name="Florida", adj="Floridian", reuse=True,
     areas=["florida_area","north_florida_area","west_florida_area"], capital=926, 
       dev=[3,3,4], trade_good="fish",
     monarchs=[dict(name="Pedro", dynasty="de la Florida", adm=2, dip=4, mil=3, birth=1398)],
     heir=dict(name="Isabel", dynasty="de la Florida", claim=87, adm=3, dip=3, mil=2, birth=1423, death=1485)),
dict(tag="CRL", name="Carolana", adj="Carolinian", reuse=False, color=[127,163,200],
     areas=["carolinas_area","south_carolina_area","south_carolina_piedmont_area","piedmont_north_america_area"],
     capital=932,    dev=[3,3,4], trade_good="grain",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Robert", dynasty="of the Two Rivers", adm=3, dip=3, mil=3, birth=1400)],
     heir=dict(name="Margaret", dynasty="of the Two Rivers", claim=86, adm=3, dip=2, mil=3, birth=1424, death=1486),
     names=["Robert","Margaret","Cape Fear","Neuse","Pamlico","Santee","Waccamaw","Catawba"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="VIR", name="Virginia", adj="Virginian", reuse=False, color=[160,176,112],
     areas=["chesapeake_area","great_valley_area","appalachia_area","westsylvania_area"], capital=950,
        dev=[3,3,4], trade_good="grain",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Pocahontas", dynasty="of the Tidewater", adm=3, dip=3, mil=3, birth=1397)],
     heir=dict(name="Raleigh", dynasty="of the Tidewater", claim=89, adm=3, dip=3, mil=3, birth=1422, death=1490),
     names=["Raleigh","Powhatan","Monacan","Shenandoah","Accomac","Roanoke","Kanawha","Rappahannock"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="MYL", name="Maryland", adj="Marylander", reuse=False, color=[192,176,96],
     areas=["maryland_area","delaware_valley_area"], capital=953,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Calvert", dynasty="of the Chesapeake", adm=2, dip=3, mil=2, birth=1405)],
     names=["Calvert","Cecil","Leonard","St. Marys","Severn","Patapsco","Potomac","Susquehannock"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="PNS", name="Pennsylvania", adj="Pennsylvanian", reuse=False, color=[176,160,128],
     areas=["susquehanna_area"], capital=955,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="William", dynasty="of the Keystone", adm=3, dip=3, mil=2, birth=1403)],
     names=["William","Juniata","Susquehanna","Lehigh","Allegheny","Monongahela","Schuylkill","Lancaster"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="HDN", name="Hudsonia", adj="Hudsonian", reuse=False, color=[94,143,176],
     areas=["new_york_area","hudson_valley_area","iroquoisia_area"], capital=965, 
       dev=[4,4,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Hiawatha", dynasty="of the Long House", adm=4, dip=4, mil=4, birth=1395)],
     heir=dict(name="Henry", dynasty="of the Long House", claim=91, adm=3, dip=4, mil=3, birth=1421, death=1494),
     names=["Hiawatha","Deganawida","Mohawk","Oneida","Onondaga","Cayuga","Seneca","Manhattan"],
     ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="NEA", name="New England", adj="New Englander", reuse=False, color=[106,127,176],
     areas=["massachusetts_bay_area","connecticut_valley_area","great_woods_area","south_iroquoisia_area",
            "maine_area","eastern_maine_area"], capital=968, 
       dev=[4,4,4], trade_good="fish",
     graphical_culture="westerngfx", extra=[481],
     monarchs=[dict(name="Priscilla Alden", dynasty="", adm=4, dip=5, mil=3, birth=1402)],
     names=["Priscilla Alden","John Winthrop","Miles Standish","William Bradford","John Carver","Edward Winslow",
            "Roger Williams","Anne Hutchinson"],
     ideas=["trade_ideas","naval_ideas","economic_ideas","defensive_ideas"]),
dict(tag="ACD", name="Acadia", adj="Acadian", reuse=False, color=[122,154,106],
     areas=["lower_acadia_area","upper_acadia_area","st_john_valley_area"], capital=982, 
       dev=[3,3,4], trade_good="fish", graphical_culture="westerngfx",
     monarchs=[dict(name="Henri", dynasty="de Montfort", adm=2, dip=4, mil=3, birth=1399)],
     heir=dict(name="Jeanne", dynasty="de Montfort", claim=85, adm=3, dip=3, mil=2, birth=1425, death=1487),
     names=["Henri","Jean","Pierre","Antoine","Philippe","Louis","Charles","Francois"],
     ideas=["defensive_ideas","trade_ideas","naval_ideas"]),
# ---------------------------------------------------------------- CANADA
dict(tag="QUE", name="Quebec", adj="Quebecois", reuse=True,
     areas=["notre_dame_mountains_area","trois_rivieres_area","lower_canada_area","laurentian_area","cote_nord_area"],
     capital=4895,    dev=[4,4,4], trade_good="fur",
     monarchs=[dict(name="Louis", dynasty="de Valois", adm=3, dip=4, mil=4, birth=1394)],
     heir=dict(name="Charles", dynasty="de Valois", claim=92, adm=4, dip=3, mil=4, birth=1420, death=1493)),
dict(tag="ONT", name="Ontario", adj="Ontarian", reuse=False, color=[138,176,128],
     areas=["upper_canada_area","huronia_area","ottawa_valley_area","upper_ontario_area","inner_ontario_area"],
     capital=991,    dev=[4,4,4], trade_good="fur",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Mackenzie", dynasty="of the Great Lakes", adm=4, dip=3, mil=4, birth=1396)],
     heir=dict(name="Laura", dynasty="of the Great Lakes", claim=90, adm=3, dip=4, mil=3, birth=1422, death=1495),
     names=["Mackenzie","Tecumseh","Ottawa","Huron","Nipissing","Algonquin","Niagara","Simcoe"],
     ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="ASB", name="Assiniboia", adj="Assiniboian", reuse=False, color=[160,168,96],
     areas=["manitoba_area","assiniboia_area","saskatchewan_area","prairies_area"], capital=1008,
        dev=[4,4,4], trade_good="fur",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Cuthbert", dynasty="of the Prairies", adm=3, dip=4, mil=4, birth=1395)],
     heir=dict(name="Marguerite", dynasty="of the Prairies", claim=89, adm=4, dip=3, mil=3, birth=1421, death=1492),
     names=["Cuthbert","Pierre","Louis","Toussaint","Jean-Baptiste","Alexandre","Angelique","Marcel"],
     ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="ALR", name="Alberta", adj="Albertan", reuse=False, color=[192,160,96],
     areas=["athabasca_area"], capital=2599,   
     dev=[3,3,3], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Banff", dynasty="of the Foothills", adm=2, dip=2, mil=3, birth=1406)],
     names=["Banff","Calgary","Edmonton","Jasper","Peace","Red Deer","Lethbridge","Medicine Hat"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="KWT", name="Keewatin", adj="Keewatin", reuse=False, color=[144,168,176],
     areas=["hudson_bay_area","james_bay_area"], capital=1005,  
      dev=[3,3,3], trade_good="fur", graphical_culture="westerngfx",
     monarchs=[dict(name="Nelson", dynasty="of the Bay", adm=2, dip=3, mil=2, birth=1408)],
     names=["Nelson","Severn","Churchill","Albany","Moose","Attawapiskat","Winisk","Fort Hope"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="TNV", name="Terra Nova", adj="Terra Novan", reuse=False, color=[176,160,136],
     areas=["newfoundland_area","labrador_area"], capital=980,  
      dev=[3,3,3], trade_good="fish", graphical_culture="westerngfx",
     monarchs=[dict(name="Gilbert", dynasty="of the Cod Banks", adm=2, dip=4, mil=2, birth=1404)],
     names=["Gilbert","Havre","Bonavista","Trinity","Conception","Placentia","Fortune","Burin"],
     ideas=["defensive_ideas","trade_ideas","naval_ideas"]),
# ---------------------------------------------------------------- MEXICO / CENTRAL AMERICA
dict(tag="SNA", name="Sonora", adj="Sonoran", reuse=True,
     areas=["sonora_area","chihuahua_area","durango_area"], capital=4577, 
       dev=[3,3,4], trade_good="copper",
     monarchs=[dict(name="Alonso", dynasty="de Guzman", adm=2, dip=4, mil=3, birth=1400)],
     heir=dict(name="Ines", dynasty="de Guzman", claim=84, adm=3, dip=3, mil=2, birth=1426, death=1488)),
dict(tag="COH", name="Coahuila", adj="Coahuilan", reuse=False, color=[192,155,107],
     areas=["northeast_mexico_area","rio_grande_area"], capital=861, 
       dev=[3,3,3], trade_good="copper", graphical_culture="westerngfx",
     monarchs=[dict(name="Rodrigo", dynasty="de Haro", adm=2, dip=3, mil=3, birth=1402)],
     names=["Rodrigo","Garcia","Sancho","Ramiro","Alfonso","Fernando","Diego","Juan"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="XAL", name="Xalisco", adj="Xaliscan", reuse=True,
     areas=["jalisco_area","nayarit_area"], capital=854,  
      dev=[3,3,4], trade_good="gold",
     monarchs=[dict(name="Tlatoani", dynasty="de Xalisco", adm=2, dip=3, mil=3, birth=1401)],
     heir=dict(name="Cihuatl", dynasty="de Xalisco", claim=85, adm=3, dip=2, mil=3, birth=1425, death=1489)),
dict(tag="ZAP", name="Oaxaca", adj="Oaxacan", reuse=True, filenote="Zapotec",
     areas=["oaxaca_area","mixteca_area"], capital=844,  
      dev=[3,3,4], trade_good="copper",
     monarchs=[dict(name="Cocijo", dynasty="of the Clouds", adm=3, dip=3, mil=3, birth=1398)],
     heir=dict(name="Xipe", dynasty="of the Clouds", claim=85, adm=2, dip=3, mil=3, birth=1424, death=1488)),
dict(tag="HND", name="Honduras", adj="Honduran", reuse=False, color=[160,128,90],
     areas=["honduras_area"], capital=840,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Lenca", dynasty="of the Mosquito Coast", adm=2, dip=2, mil=3, birth=1406)],
     names=["Lenca","Tolupan","Pech","Chorti","Miskito","Tawahka","Garifuna","Xicaque"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="NCR", name="Nicaragua", adj="Nicaraguan", reuse=False, color=[107,159,142],
     areas=["nicaragua_area","costa_rica_area"], capital=837,  
      dev=[3,3,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Nicarao", dynasty="of the Lakes", adm=2, dip=3, mil=3, birth=1401)],
     heir=dict(name="Chiltepe", dynasty="of the Lakes", claim=84, adm=2, dip=3, mil=3, birth=1427, death=1489),
     names=["Nicarao","Chiltepe","Nagrandano","Diria","Masaya","Xalteva","Ticuantepe","Orosi"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="DRN", name="Darien", adj="Darienite", reuse=False, color=[94,158,122],
     areas=["panama_area"], capital=835,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Urraca", dynasty="of the Isthmus", adm=2, dip=3, mil=2, birth=1405)],
     names=["Urraca","Chiriqui","Cueva","Cocle","Guna","Embera","Bribri","Cofan"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
# ---------------------------------------------------------------- CARIBBEAN
dict(tag="CUB", name="Cuba", adj="Cuban", reuse=True,
     areas=["cuba_area","east_cuba_area"], capital=484,  
      dev=[3,3,4], trade_good="sugar",
     monarchs=[dict(name="Hatuey", dynasty="of the Ta'no", adm=2, dip=4, mil=3, birth=1399)],
     heir=dict(name="Guama", dynasty="of the Ta'no", claim=85, adm=3, dip=3, mil=2, birth=1423, death=1487)),
dict(tag="QSQ", name="Quisqueya", adj="Quisqueyan", reuse=False, color=[111,160,192],
     areas=["hispaniola_area","dominica_area"], capital=488,  
      dev=[3,3,4], trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Enriquillo", dynasty="of the Highlands", adm=2, dip=4, mil=3, birth=1400)],
     heir=dict(name="Anacaona", dynasty="of the Highlands", claim=86, adm=3, dip=3, mil=2, birth=1424, death=1488),
     names=["Enriquillo","Anacaona","Guacanagaric","Caonabo","Bohechio","Cotubanama","Maguana","Higuey"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="XYM", name="Xaymaca", adj="Xaymacan", reuse=False, color=[127,191,127],
     extra=[487], capital=487,    dev=[3,3,3],
     trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Huareo", dynasty="of the Springs", adm=2, dip=4, mil=2, birth=1404)],
     names=["Huareo","Quao","Aguacatec","Maima","Onabe","Caguaya","Meten","Bucan"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="BQI", name="Borinquen", adj="Borinquen", reuse=False, color=[160,111,159],
     extra=[492], capital=492,    dev=[3,3,3],
     trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Agueybana", dynasty="of the Brava", adm=2, dip=4, mil=2, birth=1403)],
     names=["Agueybana","Guaybana","Mayaguez","Caguax","Arasibo","Orocobix","Jayuya","Coamex"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="ANI", name="Antillia", adj="Antillean", reuse=False, color=[134,185,217],
     areas=["leeward_islands_area","windward_islands_area","lucayan_area"], extra=[491], capital=493,
        dev=[3,3,3], trade_good="sugar",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Kalinago", dynasty="of the Reefs", adm=2, dip=4, mil=3, birth=1401)],
     heir=dict(name="Arawak", dynasty="of the Reefs", claim=83, adm=2, dip=3, mil=3, birth=1426, death=1489),
     names=["Kalinago","Arawak","Krotoa","Carbet","Tiburon","Gonave","Samana","Vieques"],
     ideas=["defensive_ideas","trade_ideas","naval_ideas"]),
# ---------------------------------------------------------------- SOUTH AMERICA NORTH
dict(tag="GYA", name="Guiana", adj="Guianan", reuse=False, color=[89,133,95],
     areas=["suriname_area"], extra=[743,744,2803], capital=744,  
      dev=[3,3,3], trade_good="fish", graphical_culture="westerngfx",
     monarchs=[dict(name="Essequibo", dynasty="of the Falls", adm=2, dip=3, mil=3, birth=1403)],
     names=["Essequibo","Berbice","Demerara","Courantyne","Maroni","Oyapock","Rupununi","Cuyuni"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="VNZ", name="Venezuela", adj="Venezuelan", reuse=True,
     areas=["venezuela_area","maracaibo_area","upper_guyana_area","eastern_llanos","central_llanos_area"],
     extra=[502], capital=831,    dev=[4,4,4],
     trade_good="grain",
     monarchs=[dict(name="Romulo", dynasty="de los Llanos", adm=3, dip=4, mil=4, birth=1396)],
     heir=dict(name="Bolivar", dynasty="de los Llanos", claim=91, adm=4, dip=4, mil=4, birth=1420, death=1494)),
dict(tag="QTO", name="Quito", adj="Quitean", reuse=True,
     areas=["quito_area","iquitos_area"], capital=820,  
      dev=[3,3,4], trade_good="grain",
     monarchs=[dict(name="Huaypalcon", dynasty="Caracara", adm=2, dip=4, mil=3, birth=1398)],
     heir=dict(name="Luyes", dynasty="Caracara", claim=88, adm=3, dip=3, mil=3, birth=1423, death=1489)),
dict(tag="CSU", name="Cusco", adj="Cuscan", reuse=True,
     areas=["kuntisuyu_area"], capital=808,   
     dev=[3,3,4], trade_good="grain",
     monarchs=[dict(name="Pachacuti", dynasty="Inka", adm=4, dip=3, mil=4, birth=1395)],
     heir=dict(name="Tupac", dynasty="Inka", claim=90, adm=3, dip=3, mil=4, birth=1420, death=1492)),
# ---------------------------------------------------------------- ANDES / SOUTH
dict(tag="CHL", name="Chile", adj="Chilean", reuse=True,
     areas=["central_chile_area","nehuenken_area","southern_chile_area","northern_chile_area","cuyo_area"],
     capital=787,    dev=[4,4,4], trade_good="grain",
     monarchs=[dict(name="Lautaro", dynasty="of the Long Coast", adm=3, dip=3, mil=5, birth=1394)],
     heir=dict(name="Caupolican", dynasty="of the Long Coast", claim=91, adm=3, dip=3, mil=4, birth=1419, death=1496)),
dict(tag="TCM", name="Tucuman", adj="Tucumanian", reuse=False, color=[168,155,90],
     areas=["tucuman_area","jujuy_area"], capital=791,  
      dev=[3,3,3], trade_good="grain", graphical_culture="southamericagfx",
     monarchs=[dict(name="Cacique", dynasty="del Norte", adm=2, dip=3, mil=3, birth=1404)],
     names=["Cacique","Sumalao","Amaicha","Quilmes","Purmamarca","Tilcara","Cachi","Molinos"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="PRG", name="Paraguay", adj="Paraguayan", reuse=True,
     areas=["paraguay_area","misiones_area","chaco_area"], capital=775, 
       dev=[3,3,4], trade_good="grain",
     monarchs=[dict(name="Yvoty", dynasty="de la Asuncion", adm=2, dip=4, mil=3, birth=1399)],
     heir=dict(name="Guarani", dynasty="de la Asuncion", claim=85, adm=3, dip=3, mil=2, birth=1424, death=1488)),
dict(tag="LAP", name="La Plata", adj="Platinean", reuse=True,
     areas=["buenos_aires_area","southern_pampas_area","bahia_blanca_area"], capital=2848, 
       dev=[4,4,4], trade_good="grain",
     monarchs=[dict(name="Estanislao", dynasty="del Rio de la Plata", adm=3, dip=4, mil=4, birth=1396)],
     heir=dict(name="Catalina", dynasty="del Rio de la Plata", claim=90, adm=4, dip=4, mil=3, birth=1421, death=1493)),
dict(tag="URY", name="Uruguay", adj="Uruguayan", reuse=False, color=[111,176,192],
     areas=["banda_oriental_area"], capital=772,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Artigas", dynasty="of the Banda", adm=2, dip=3, mil=3, birth=1403)],
     names=["Artigas","Tacuarembo","Salto","Paysandu","Durazno","Cerro Largo","Treinta y Tres","Rocha"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="PTN", name="Patagonia", adj="Patagonian", reuse=False, color=[154,168,160],
     areas=["patagonia_area","patagonian_andes","south_atlantic_islands_area"], capital=781,
        dev=[3,3,3], trade_good="fish",
     graphical_culture="southamericagfx",
     monarchs=[dict(name="Tehuelche", dynasty="of the Wind", adm=2, dip=3, mil=3, birth=1402)],
     names=["Tehuelche","Selknam","Yaghan","Chono","Puelche","Mapuche","Huiliche","Kawesqar"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
# ---------------------------------------------------------------- BRAZIL
dict(tag="AMZ", name="Amazonia", adj="Amazonian", reuse=False, color=[78,143,78],
     areas=["amazon_area","grao_para_area","amapa_area"], extra=[1802,1803], capital=2889, 
       dev=[2,2,2], trade_good="fish",
     graphical_culture="southamericagfx",
     monarchs=[dict(name="Cunhambebe", dynasty="Tupinamba", adm=2, dip=3, mil=4, birth=1398)],
     heir=dict(name="Tibirica", dynasty="Tupinamba", claim=87, adm=2, dip=2, mil=4, birth=1424, death=1490),
     names=["Cunhambebe","Tibirica","Jagoanharo","Paraguacu","Aimbire","Moacir","Iperu","Caramuru"],
     ideas=["defensive_ideas","offensive_ideas","economic_ideas"]),
dict(tag="MRN", name="Maranhao", adj="Maranhense", reuse=False, color=[176,130,90],
     areas=["maranhao_area","piaui_area"], capital=749,  
      dev=[3,3,4], trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Nuno", dynasty="de Aguiar", adm=2, dip=3, mil=3, birth=1402)],
     heir=dict(name="Beatriz", dynasty="de Aguiar", claim=84, adm=3, dip=2, mil=3, birth=1426, death=1488),
     names=["Nuno","Goncalo","Rodrigo","Duarte","Joao","Manuel","Vasco","Melchior"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="PNB", name="Pernambuco", adj="Pernambucan", reuse=False, color=[200,107,90],
     areas=["pernambuco_area","ceara_area"], capital=754,  
      dev=[3,3,4], trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Duarte", dynasty="de Coelho", adm=2, dip=3, mil=3, birth=1401)],
     heir=dict(name="Isabel", dynasty="de Coelho", claim=86, adm=3, dip=3, mil=2, birth=1425, death=1489),
     names=["Duarte","Afonso","Gaspar","Lopo","Ruy","Tristao","Fernao","Sancho"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="BYA", name="Bahia", adj="Baiano", reuse=False, color=[208,122,58],
     areas=["bahia_area","sao_francisco_area","diamantina_area"], capital=756, 
       dev=[3,3,4], trade_good="sugar", graphical_culture="westerngfx",
     monarchs=[dict(name="Tomé", dynasty="de Sousa", adm=3, dip=3, mil=3, birth=1398)],
     heir=dict(name="Garcia", dynasty="de Sousa", claim=85, adm=2, dip=3, mil=3, birth=1423, death=1491),
     names=["Tome","Garcia","Mem","Pero","Lourenco","Brito","Caminha","Anchieta"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="MGX", name="Minas", adj="Mineiro", reuse=False, color=[155,127,90],
     areas=["minas_gerais_area","goias_area"], capital=765,  
      dev=[3,3,4], trade_good="gold", graphical_culture="westerngfx",
     monarchs=[dict(name="Borba", dynasty="Gato de Cascais", adm=2, dip=3, mil=3, birth=1400)],
     heir=dict(name="Fernao", dynasty="Gato de Cascais", claim=83, adm=3, dip=2, mil=3, birth=1424, death=1490),
     names=["Borba","Bartholomeu","Sao Paulo","Antonio","Simao","Jeronymo","Alvarenga","Guimaraes"],
     ideas=["defensive_ideas","economic_ideas","trade_ideas"]),
dict(tag="RDJ", name="Rio", adj="Carioca", reuse=False, color=[90,160,176],
     areas=["rio_de_janeiro_area"], capital=763,  
      dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Estacio de Sa", dynasty="", adm=3, dip=4, mil=2, birth=1402)],
     names=["Estacio de Sa","Mem de Sa","Salvador Correia","Jeronimo de Albuquerque","Martim Afonso",
            "Duarte da Costa","Francisco de Souza","Diogo Botelho"],
     ideas=["trade_ideas","naval_ideas","economic_ideas"]),
dict(tag="SPO", name="Sao Paulo", adj="Paulistan", reuse=False, color=[79,123,160],
     areas=["sao_paolo_area","west_sao_paolo_area","pontal_area"], capital=766, 
       dev=[4,4,4], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Martim", dynasty="Afonso de Souza", adm=3, dip=4, mil=4, birth=1395)],
     heir=dict(name="Manoel", dynasty="Afonso de Souza", claim=90, adm=4, dip=3, mil=3, birth=1420, death=1493),
     names=["Martim","Manoel","Sao Vicente","Bertioga","Piratininga","Santo Andre","Mogi","Sorocaba"],
     ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="RGR", name="Rio Grande", adj="Riograndense", reuse=False, color=[160,176,90],
     areas=["rio_grande_do_sol_area"], capital=2857,   
     dev=[3,3,3], trade_good="grain", graphical_culture="westerngfx",
     monarchs=[dict(name="Laguna", dynasty="de los Pampas", adm=2, dip=3, mil=3, birth=1405)],
     names=["Laguna","Santos","Porto Alegre","Pelotas","Rio Pardo","Viamao","Caxias","Bage"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
dict(tag="MTG", name="Mato Grosso", adj="Matogrossan", reuse=False, color=[127,160,106],
     areas=["mato_grosso_area","ofaie_area","guapore_area"], capital=2888, 
       dev=[3,3,4], trade_good="gold", graphical_culture="westerngfx",
     monarchs=[dict(name="Cuiaba", dynasty="dos Bandeirantes", adm=2, dip=3, mil=3, birth=1401)],
     heir=dict(name="Bororo", dynasty="dos Bandeirantes", claim=85, adm=3, dip=2, mil=3, birth=1425, death=1491),
     names=["Cuiaba","Bororo","Xingu","Aripuana","Juruena","Pantanal","Parecis","Guapore"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
# ---------------------------------------------------------------- ARCTIC / NORTH ATLANTIC
dict(tag="GRL", name="Greenland", adj="Greenlandic", reuse=False, color=[186,206,216],
     areas=["greenland_area"], capital=1104,   
     dev=[2,2,2], trade_good="fish", culture="icelandic", religion="catholic",
     graphical_culture="westerngfx",
     monarchs=[dict(name="Eirik", dynasty="Thorvaldsson", adm=3, dip=3, mil=3, birth=1402)],
     names=["Eirik","Snorri","Thorgils","Orm","Koll","Gunnar","Thorvald","Bjarni"],
     ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
]

# Areas that exist but are intentionally not assigned to any realm.
# Sea zones auto-skip (no province files):
SKIP_AREAS = []

# vanilla tags that keep their 1444 territory: their provinces/defs/flags/loc
# stay vanilla, but gen_mod DOES write ONE override: their history/countries
# preamble is patched to government=monarchy + feudalism_reform + a dev-derived rank
# (see gen_mod.restore_override). gen_mod must not write any other file for
# them and carves their provinces out of the mod realms.
RESTORED = {
    "AZT": [852, 853, 2645, 4570, 4571],
    "CCQ": [794, 2837, 2838],
    "CHM": [812, 816, 2821, 2822, 2826],
    "CHT": [839, 2637],
    "CJA": [813, 2824],
    "CLA": [802, 804, 2947],
    "CLM": [2643, 2657, 4579, 4580],
    "CNP": [845, 2650],
    "COC": [846, 2652, 4591],
    "COI": [2646, 4581],
    "CRA": [795, 2835, 2941, 2942],
    "CTM": [843, 2634, 4589],
    "CYA": [2823, 2943],
    "HJA": [814, 2825, 2827],
    "HST": [858, 2641],
    "ICM": [809],
    "ITZ": [842, 4588, 4594],
    "KAQ": [2636, 2653],
    "KER": [4632],
    "KIC": [841, 4587],
    "LAC": [2635, 4585, 4586],
    "MAT": [2623, 2626, 4572],
    "MCA": [825, 832, 4603],
    "MIX": [847, 2629],
    "OTO": [2642, 4573, 4641],
    "PCJ": [797, 2831, 2940, 2946],
    "TAR": [2622, 2624, 4574, 4575],
    "TEO": [2628, 4582],
    "TLA": [849, 851, 2627, 2648],
    "TLX": [850, 2644, 4583],
    "TON": [2617, 2621, 4640],
    "TOT": [848, 2647, 4598],
    "WKA": [810, 811],
    "XIU": [2633, 2651, 4590],
    "YOK": [2630, 2631, 2632],
}

# The 9 realms cut out of 1444 (their areas revert to vanilla ownership).
# gen_mod redistributes the leftover non-restored provinces ("orphans") to
# the nearest surviving realm, so every province still has an owner.
GUTTED = [
    ("MEX", ["mexico_area", "puebla_area", "guerrero_area", "guanajuato_area",
             "zacatecas_area", "gran_chichimeca_area"]),
    ("MHC", ["michoacan_area", "tierra_caliente_area"]),
    ("VRC", ["huasteca_area", "eastern_mexico_area"]),
    ("MAY", ["yucatan_area", "east_yucatan_area", "campeche_area"]),
    ("CXA", ["chiapas_area"]),
    ("GTM", ["guatemala_area", "guatemala_lowlands_area"]),
    ("COL", ["bogota_area", "cordillera_occidental_area", "popayan_area",
             "colombian_amazonas_area", "coquivacoa_area", "western_llanos"]),
    ("PEU", ["peruan_coast", "huanuco_area", "cajamarca_area", "chimor_area", "ucayali_area"]),
    ("BOL", ["antisuyu_area", "potosi_area", "upper_peru", "moxos_area", "beni_area"]),
]


# ------------------------------------------------------------------
# NEW_TRIBES - new custom tribal tags, one province each, carved from the
# big realms so every region keeps both tribal OPMs and a viable kingdom.
# The vanilla province NAME is the historical group (Pomo, Nootka, ...);
# there is no vanilla def/loc/flag for these tags, so gen builds defs and
# localisation like the non-reuse realms, and flags stay on flags_needed.
# Cult names: real leaders where recorded (Saturiwa, Outina, Ivitachuco,
# Tonela) or attested band/chiefdom names; monarchs carry no dynasty,
# matching vanilla native style.
# ------------------------------------------------------------------
NEW_TRIBES = [
    # California (CAL 18 -> 12 provinces left)
    dict(tag="PMO", name="Pomo", adj="Pomo", prov=871, culture="chinook",
         religion="totemism", color=[30, 92, 66], graphical_culture="northamericagfx",
         monarchs=[dict(name="Kulantai", adm=2, dip=2, mil=2, birth=1409)],
         heir=dict(name="Shanel", claim=80, adm=2, dip=2, mil=2, birth=1430, death=1495),
         names=["Kulantai","Shanel","Tsawai","Bakayuk","Sokei","Elakmi"],
         ideas=["pmo_ideas"]),
    dict(tag="MWK", name="Miwok", adj="Miwok", prov=2021, culture="yokuts",
         religion="totemism", color=[109, 72, 34], graphical_culture="northamericagfx",
         monarchs=[dict(name="Kaku", adm=2, dip=3, mil=2, birth=1406)],
         heir=dict(name="Hoyoma", claim=75, adm=2, dip=2, mil=3, birth=1428, death=1492),
         names=["Kaku","Hoyoma","Wiyaka","Saxui","Tolemne","Puyut"],
         ideas=["mwk_ideas"]),
    dict(tag="MDU", name="Maidu", adj="Maidu", prov=2479, culture="yokuts",
         religion="totemism", color=[134, 146, 58], graphical_culture="northamericagfx",
         monarchs=[dict(name="Wepam", adm=2, dip=2, mil=3, birth=1410)],
         heir=dict(name="Kojak", claim=70, adm=3, dip=2, mil=2, birth=1431, death=1497),
         names=["Wepam","Kojak","Hankali","Tosik","Yumano","Pule"],
         ideas=["mdu_ideas"]),
    dict(tag="WNT", name="Wintun", adj="Wintun", prov=4638, culture="yokuts",
         religion="totemism", color=[46, 105, 121], graphical_culture="northamericagfx",
         monarchs=[dict(name="Nomlaki", adm=3, dip=2, mil=2, birth=1405)],
         heir=dict(name="Wolok", claim=85, adm=2, dip=2, mil=2, birth=1426, death=1490),
         names=["Nomlaki","Wolok","Paskenta","Tsamkai","Hewan","Sawal"],
         ideas=["wnt_ideas"]),
    dict(tag="OHO", name="Ohlone", adj="Ohlone", prov=4637, culture="yokuts",
         religion="totemism", color=[158, 110, 40], graphical_culture="northamericagfx",
         monarchs=[dict(name="Mutsun", adm=2, dip=2, mil=2, birth=1408)],
         heir=dict(name="Rumsen", claim=80, adm=2, dip=3, mil=2, birth=1430, death=1494),
         names=["Mutsun","Rumsen","Chochenyo","Karkin","Tamien","Yelamu"],
         ideas=["oho_ideas"]),
    # Northwest coast (CSC 20 -> 16 provinces left)
    dict(tag="NKT", name="Nootka", adj="Nootkan", prov=972, culture="aleutian",
         religion="totemism", color=[56, 80, 140], graphical_culture="northamericagfx",
         monarchs=[dict(name="Tloqwa", adm=2, dip=3, mil=2, birth=1407)],
         heir=dict(name="Tsawalk", claim=78, adm=2, dip=2, mil=3, birth=1429, death=1491),
         names=["Tloqwa","Tsawalk","Hawilth","Yaquotl","Nookmi","Hesquiat"],
         ideas=["nkt_ideas"]),
    dict(tag="KWK", name="Kwakiutl", adj="Kwakiutl", prov=974, culture="aleutian",
         religion="totemism", color=[99, 44, 99], graphical_culture="northamericagfx",
         monarchs=[dict(name="Gwayasdams", adm=3, dip=2, mil=2, birth=1404)],
         heir=dict(name="Hamatsa", claim=82, adm=2, dip=3, mil=2, birth=1427, death=1496),
         names=["Gwayasdams","Hamatsa","Tsekame","Tsawatti","Klolwa","Nagwis"],
         ideas=["kwk_ideas"]),
    dict(tag="TSM", name="Tsimshian", adj="Tsimshian", prov=975, culture="chinook",
         religion="totemism", color=[160, 66, 44], graphical_culture="northamericagfx",
         monarchs=[dict(name="Wisaks", adm=2, dip=2, mil=3, birth=1411)],
         heir=dict(name="Gwaas", claim=72, adm=2, dip=2, mil=2, birth=1432, death=1499),
         names=["Wisaks","Gwaas","Laxgyibuu","Nislagi","Ts'ibasa","Daaxan"],
         ideas=["tsm_ideas"]),
    dict(tag="HLS", name="Heiltsuk", adj="Heiltsuk", prov=2610, culture="salish",
         religion="totemism", color=[44, 130, 110], graphical_culture="northamericagfx",
         monarchs=[dict(name="Qinax", adm=2, dip=3, mil=3, birth=1406)],
         heir=dict(name="Tlabit", claim=86, adm=3, dip=2, mil=2, birth=1428, death=1493),
         names=["Qinax","Tlabit","Huaxta","Kaxla","Susa","Waklas"],
         ideas=["hls_ideas"]),
    # Texas coast (TEX 16 -> 13 provinces left; capital moved to Comanche 885)
    dict(tag="KRN", name="Karankawa", adj="Karankawan", prov=884, culture="caddo",
         religion="totemism", color=[128, 120, 36], graphical_culture="northamericagfx",
         monarchs=[dict(name="Kukan", adm=2, dip=2, mil=2, birth=1409)],
         heir=dict(name="Tamkol", claim=74, adm=2, dip=2, mil=3, birth=1430, death=1490),
         names=["Kukan","Tamkol","Aranama","Savan","Karank","Toya"],
         ideas=["krn_ideas"]),
    dict(tag="TKA", name="Tonkawa", adj="Tonkawan", prov=887, culture="caddo",
         religion="totemism", color=[88, 66, 44], graphical_culture="northamericagfx",
         monarchs=[dict(name="Yojuane", adm=2, dip=3, mil=2, birth=1405)],
         heir=dict(name="Mayeye", claim=88, adm=2, dip=2, mil=2, birth=1426, death=1492),
         names=["Yojuane","Mayeye","Ervipiame","Cava","Sana","Toho"],
         ideas=["tka_ideas"]),
    dict(tag="ATP", name="Atakapa", adj="Atakapan", prov=888, culture="caddo",
         religion="totemism", color=[52, 112, 150], graphical_culture="northamericagfx",
         monarchs=[dict(name="Akokisa", adm=3, dip=2, mil=2, birth=1410)],
         heir=dict(name="Bidai", claim=80, adm=2, dip=3, mil=2, birth=1431, death=1498),
         names=["Akokisa","Bidai","Hakipaki","Deadoses","Quasmigdo","Tlo"],
         ideas=["atp_ideas"]),
    # Florida (FLO 13 -> 10 provinces left)
    dict(tag="TMU", name="Timucua", adj="Timucuan", prov=927, culture="yamasee",
         religion="totemism", color=[128, 56, 66], graphical_culture="northamericagfx",
         monarchs=[dict(name="Saturiwa", adm=2, dip=3, mil=3, birth=1405)],
         heir=dict(name="Outina", claim=84, adm=3, dip=2, mil=2, birth=1427, death=1495),
         names=["Saturiwa","Outina","Tacatucuru","Utina","Paracusi","Anoya"],
         ideas=["tmu_ideas"]),
    dict(tag="APC", name="Apalachee", adj="Apalachee", prov=928, culture="creek",
         religion="totemism", color=[74, 96, 44], graphical_culture="northamericagfx",
         monarchs=[dict(name="Ivitachuco", adm=3, dip=2, mil=2, birth=1408)],
         heir=dict(name="Lacata", claim=76, adm=2, dip=2, mil=2, birth=1429, death=1491),
         names=["Ivitachuco","Lacata","Balbali","Calahuchi","Autauga","Anaicape"],
         ideas=["apc_ideas"]),
    dict(tag="CLS", name="Calusa", adj="Calusan", prov=2535, culture="yamasee",
         religion="totemism", color=[36, 120, 156], graphical_culture="northamericagfx",
         monarchs=[dict(name="Tonela", adm=2, dip=2, mil=3, birth=1412)],
         heir=dict(name="Ucita", claim=70, adm=2, dip=3, mil=2, birth=1433, death=1496),
         names=["Tonela","Ucita","Carlos","Felipe","Cholok","Mocoso"],
         ideas=["cls_ideas"]),
    # Caribbean (ANI 13 -> 11 provinces left)
    dict(tag="KLG", name="Kalinago", adj="Kalinago", prov=495, culture="carib",
         religion="animism", color=[160, 196, 196], graphical_culture="westerngfx",
         monarchs=[dict(name="Cacimar", adm=2, dip=3, mil=3, birth=1406)],
         heir=dict(name="Irra", claim=82, adm=2, dip=2, mil=2, birth=1428, death=1492),
         names=["Cacimar","Arnaut","Daguao","Tibiri"],
         ideas=["klg_ideas"]),
    dict(tag="LCN", name="Lucayan", adj="Lucayan", prov=482, culture="arawak",
         religion="animism", color=[198, 150, 40], graphical_culture="westerngfx",
         monarchs=[dict(name="Comogre", adm=3, dip=3, mil=2, birth=1405)],
         heir=dict(name="Guarocuya", claim=84, adm=3, dip=2, mil=2, birth=1427, death=1491),
         names=["Comogre","Guaora","Maramor","Anacaona"],
         ideas=["lcn_ideas"]),
    # Southern cone (CHL 20 -> 19 provinces left)
    dict(tag="MAP", name="Mapuche", adj="Mapuche", prov=785, culture="mapuche",
         religion="animism", color=[90, 40, 120], graphical_culture="southamericagfx",
         monarchs=[dict(name="Lautaro", adm=2, dip=3, mil=4, birth=1404)],
         heir=dict(name="Pelantaro", claim=86, adm=3, dip=3, mil=3, birth=1426, death=1490),
         names=["Lautaro","Caupolican","Colocolo","Antilen","Millarapue"],
         ideas=["map_ideas"]),
    # Paraguay/Parana (PRG 16 -> 15 provinces left)
    dict(tag="GRN", name="Guarani", adj="Guarani", prov=776, culture="guarani",
         religion="animism", color=[30, 120, 60], graphical_culture="southamericagfx",
         monarchs=[dict(name="Tabare", adm=2, dip=4, mil=3, birth=1407)],
         heir=dict(name="Curupi", claim=80, adm=2, dip=3, mil=2, birth=1429, death=1493),
         names=["Tabare","Maracaja","Yaguaron","Arapy"],
         ideas=["grn_ideas"]),
    # Cascadia (CSC 15 -> 14 provinces left)
    dict(tag="KTX", name="Ktunaxa", adj="Ktunaxa", prov=2003, culture="shoshone",
         religion="totemism", color=[60, 90, 150], graphical_culture="northamericagfx",
         monarchs=[dict(name="Kakohana", adm=3, dip=3, mil=2, birth=1403)],
         heir=dict(name="Temaq", claim=78, adm=2, dip=3, mil=2, birth=1425, death=1489),
         names=["Kakohana","Palkan","Yaaxa"],
         ideas=["ktx_ideas"]),
]


# ------------------------------------------------------------------
# FORMABLES - federation and region tags that can be formed in-game.
# None of these owns provinces at 1444 (no province files are written
# for them). The 6 federation tags exist in vanilla but own nothing;
# we override their history so change_tag applies the mod's feudal-monarchy
# template instead of vanilla government=native.
#   tag, name            - vanilla formable tag + name
#   culture, religion    - template applied on formation
#   capital              - vanilla capital province (member-owned)
#   members              - member tribe tags (potential/allow)
#   provs                - their 1444 provinces (allow/cores)
# ------------------------------------------------------------------
FORMABLES = [
    dict(tag="IRO", name="Iroquois", culture="iroquois", religion="totemism", capital=960,
         members=["ONO","MOH","ONE","CAY","SEN"], provs=[960,961,964,959,958]),
    dict(tag="HUR", name="Huron", culture="huron", religion="totemism", capital=988,
         members=["ATT","AGG","ARN","TAH"], provs=[988,989,2585,2670]),
    dict(tag="ILL", name="Illiniwek", culture="illini", religion="totemism", capital=915,
         members=["PEO","CAO","KSK"], provs=[915,917,916]),
    dict(tag="CRE", name="Creek", culture="creek", religion="totemism", capital=925,
         members=["COW","KSI","COO","SAT","ABI","ETO"], provs=[925,930,931,2527,2531,2540]),
    dict(tag="PUE", name="Pueblo", culture="pueblo", religion="totemism", capital=880,
         members=["OHK","ZNI","ACO","ISL"], provs=[880,2494,2495,4631]),
    dict(tag="SHA", name="Shawnee", culture="shawnee", religion="totemism", capital=2525,
         members=["CLG","KSP","HWK"], provs=[2525,2526,4888]),
]

# Region-based formables, modeled on vanilla BrazilNation / LaPlataNation but
# usable by the mod's own realms (vanilla ones are gated on colonial/native).
# MEX/PEU/COL: vanilla def + history + flag reused as-is (no files written).
# ARG/BOL/GTM: new tags - def, history, loc, country_tags entry are generated
#      (flags still needed, see gfx/flags).
FORMABLE_REGIONS = [
    dict(tag="BRZ", name="Brazil", region="brazil_region", colonial="colonial_brazil", value=10),
    dict(tag="ARG", name="Argentina", adj="Argentine", region="la_plata_region", colonial="colonial_la_plata", value=8,
         new_def=True, color=[116,172,223], graphical_culture="westerngfx",
         culture="platinean", religion="catholic", capital=778,
         names=["Juan","Jose","Manuel","Rodrigo","Fernando","Carlos","Diego","Ramon",
                "Pedro","Martin","Alonso","Francisco","Gonzalo","Hernando","Iago","Vicente"],
         ideas=["defensive_ideas","religious_ideas","offensive_ideas","trade_ideas",
                "diplomatic_ideas","administrative_ideas","spy_ideas","quality_ideas"]),
    dict(tag="MEX", name="Mexico", region="mexico_region", colonial="colonial_mexico", value=10),
    dict(tag="PEU", name="Peru", region="peru_region", colonial="colonial_peru", value=10),
    dict(tag="COL", name="Colombia", region="colombia_region", colonial="colonial_colombia", value=10),
    dict(tag="BOL", name="Bolivia", adj="Bolivian", region="upper_peru_region", colonial="colonial_peru", value=8,
         new_def=True, color=[176,111,90], graphical_culture="southamericagfx",
         culture="aimara", religion="catholic", capital=2835,
         names=["Colla","Tiahuanaco","Potosi","Chuquisaca","Oruro","Cochabamba","Santa Cruz","Beni"],
         ideas=["defensive_ideas","offensive_ideas","economic_ideas","trade_ideas"]),
    dict(tag="GTM", name="Guatemala", adj="Guatemalan", region="central_america_region", colonial="colonial_mexico", value=8,
         new_def=True, color=[125,160,138], graphical_culture="westerngfx",
         culture="highland_mayan", religion="catholic", capital=841,
         names=["Iximche","Tecun","Utatlan","Zakuleu","Tz'utujil","K'iche","Peten","Mam"],
         ideas=["defensive_ideas","trade_ideas","economic_ideas"]),
    dict(tag="RCA", name="Republic of California", adj="Californian",
         region="california_region", colonial="colonial_california", value=10,
         new_def=True, color=[240,196,66], graphical_culture="westerngfx",
         culture="piman", religion="catholic", capital=868,
         names=["Jose","Juan","Carlos","Manuel","Diego","Ramon","Pedro","Francisco",
                "Antonio","Miguel","Rafael","Alejandro","Tomas","Luis","Arturo","Vicente"],
         ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas",
                "religious_ideas"]),
    dict(tag="GLC", name="Gulf Coast Federation", adj="Gulf Coast",
         region="rio_grande_region", colonial="colonial_mexico", value=8,
         new_def=True, color=[0,150,150], graphical_culture="westerngfx",
         culture="caddo", religion="catholic", capital=885,
         names=["Juan","Jose","Carlos","Manuel","Antonio","Francisco","Jesus",
                "Diego","Ramon","Pedro","Miguel","Rafael","Tomas","Luis","Ignacio","Vicente"],
         ideas=["defensive_ideas","offensive_ideas","trade_ideas","economic_ideas"]),
    dict(tag="MCP", name="Mississippi Confederation", adj="Mississippian",
         region="mississippi_region", colonial="colonial_louisiana", value=10,
         new_def=True, color=[55,125,45], graphical_culture="westerngfx",
         culture="choctaw", religion="catholic", capital=893,
         names=["Tuskaloosa","Pascagoula","Biloxi","Yazoo","Natchez","Chitimacha",
                "Quapaw","Alibamu","Tallahatchie","Yalobusha","Chickasaw","Choctaw"],
         ideas=["defensive_ideas","religious_ideas","offensive_ideas","economic_ideas",
                "trade_ideas"]),
    dict(tag="FWN", name="Federation of the West Indies", adj="West Indian",
         region="carribeans_region", colonial="colonial_the_carribean", value=8,
         new_def=True, color=[0,165,205], graphical_culture="westerngfx",
         culture="arawak", religion="catholic", capital=488,
         names=["Guarionex","Caonabo","Hatuey","Enriquillo","Agueybana","Urayoan",
                "Mabodomaca","Orocobix","Caguax","Guacanagarix","Anacaona","Mayobanex",
                "Cotubanama","Guama","Humacao","Daguayo"],
         ideas=["defensive_ideas","naval_ideas","trade_ideas","economic_ideas"]),
]
